[package]
name = "axum-csrf-sync-pattern"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
async-session = "3.0.0"
axum = "0.5.17"
axum-sessions = "0.3.2"
base64 = "0.13.1"
rand = "0.8.5"
thiserror = "1.0.37"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread"] }
tower = "0.4.13"
tracing = "0.1.37"

[dev-dependencies]
tokio-test = "0.4.2"
tower-http = { version = "0.3.4", features = ["cors"] }
