[package]
name = "cross-site"
authors = ["LeoniePhiline <awoo@posteo.de>"]
version = "0.2.2"
edition = "2021"
publish = false

[dependencies]
axum = "0.6.1"
axum-csrf-sync-pattern = { path = "../../" }
axum-sessions = "0.4.1"
color-eyre = "0.6.2"
rand = "0.8.5"
tokio = { version = "1.22.0", features = ["macros", "rt", "rt-multi-thread"] }
tower = "0.4.13"
tower-http = { version = "0.3.4", features = ["cors"] }
tracing-subscriber = "0.3.16"
