[package]
name = "same-site"
authors = ["LeoniePhiline <awoo@posteo.de>"]
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
async-session = "3.0.0"
axum = "0.5.17"
axum-csrf-sync-pattern = { path = "../../" }
axum-sessions = "0.3.2"
color-eyre = "0.6.2"
rand = "0.8.5"
tokio = { version = "1.21.2", features = ["macros", "rt", "rt-multi-thread"] }
tower = "0.4.13"
tracing-subscriber = "0.3.16"